import { mauve, mauveA, violet, violetA } from "@radix-ui/colors";
import { createStitches } from "@stitches/react";

export const {
  config,
  createTheme,
  css,
  getCssText,
  globalCss,
  keyframes,
  prefix,
  reset,
  styled,
  theme,
} = createStitches({
  theme: {
    colors: {
      ...mauve,
      ...mauveA,
      ...violet,
      ...violetA,
    },
    fonts: {
      sans: "Inter, sans-serif",
    },
    lineHeights: {
      body: 1.567,
      headings: 1.343,
    },
    radii: {
      sm: "4px",
      md: "8px",
      lg: "12px",
      pill: "99999px",
    },
    shadows: {
      sm: "0px 2px 5px $colors$mauveA4",
      md: "0px 4px 8px $colors$mauveA4",
      lg: "0px 8px 16px $colors$mauveA4",
    },
    sizes: {
      pixel: "1px",
      1: "5px",
      2: "10px",
      3: "15px",
      4: "20px",
      5: "25px",
      6: "30px",
      7: "35px",
      8: "40px",
      9: "45px",
      10: "50px",
      sm: "320px",
      md: "480px",
      lg: "720px",
      xl: "1024px",
      prose: "720px",
      page: "1148px",
    },
    space: {
      pixel: "1px",
      1: "5px",
      2: "10px",
      3: "15px",
      4: "20px",
      5: "25px",
      6: "30px",
      7: "35px",
      8: "40px",
      9: "45px",
      10: "50px",
      12: "60px",
      16: "80px",
      20: "100px",
      30: "150px",
    },
  },
  media: {
    sm: "(min-width: 320px)",
    md: "(min-width: 480px)",
    lg: "(min-width: 720px)",
  },
  prefix: "mercury",
});
